version: '3.4'

name: theater-backend

networks:
  theater_dev:
    name: theater_dev
  services_dev:
    external: true
    name: services_dev

services:
  theater-api:
    image: ${DOCKER_REGISTRY-}theater-api
    container_name: 'theater-api'
    build: 
      context: .
      dockerfile: theater-api.dockerfile
    ports:
      - "8080:8080"
    networks:
      - services_dev
      - theater_dev
    env_file:
      - .env-dev

  theater-signalr:
    image: ${DOCKER_REGISTRY-}theater-signalr
    container_name: 'theater-signalR'
    build: 
      context: .
      dockerfile: theater-signalr.dockerfile
    ports:
      - "8081:8080"
    networks:
      - services_dev
      - theater_dev
    env_file:
      - .env-dev
    depends_on:
      - theater-api