version: '3.4'

services:
  # rabbitmq:
  #   image: rabbitmq:3.9.7-management
  #   container_name: 'rabbitmq'
  #   hostname: myrabbitmq
  #   restart: unless-stopped
  #   ports:
  #     - 5672:5672 # AMQP protocol port
  #     - 15672:15672 # UI for images ...:3-management
  #   healthcheck:
  #     test: rabbitmq-diagnostics -q ping
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     #start_period: 0s
  #   #volumes:
  #   #    - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #   #    - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #   env_file:
  #     - ncsi.env
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_REGION: eu-west-1
    command: server --console-address ":9001" /data
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  dev-db-data:
