version: '3.4'

networks:
  theater-dev:
    driver: bridge

services:
  theater:
    image: ${DOCKER_REGISTRY-}theater-api
    container_name: 'theater-api'
    build: 
      context: .
      dockerfile: theater-api.dockerfile
    ports:
      - "8080:8080"
    networks:
      - theater-dev
    env_file:
      - .env-dev
    depends_on:
      - minio
      - postgres
      - rabbitmq
      - redis

  theater-signalr:
    image: ${DOCKER_REGISTRY-}theater-signalr
    container_name: 'theater-signalR'
    build: 
      context: .
      dockerfile: theater-signalr.dockerfile
    ports:
      - "8081:8080"
    networks:
      - theater-dev
    env_file:
      - .env-dev
    depends_on:
      - minio
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: postgres:latest
    container_name: 'postgres'
    env_file:
      - .env-dev
    command: -p 5434
    restart: always
    expose:
      - "5434"
    ports:
      - '5434:5434'
    networks:
      - theater-dev
    volumes: 
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.7-management
    container_name: 'rabbitmq'
    env_file:
      - .env-dev
    hostname: myrabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # UI for images ...:3-management
    networks:
      - theater-dev
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  minio:
    image: minio/minio:latest
    container_name: 'minio'
    env_file:
      - .env-dev
    command: server --console-address ":9001" /data
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - theater-dev

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    networks:
      - theater-dev

volumes:
  redisdata:
  postgres:
    driver: local
